import * as path from 'node:path';

export type Language =
  | 'typescript'
  | 'tsx'
  | 'javascript'
  | 'jsx'
  | 'python'
  | 'java'
  | 'go'
  | 'csharp'
  | 'ruby'
  | 'php'
  | 'rust'
  | 'kotlin'
  | 'swift'
  | 'scala'
  | 'sql'
  | 'shell'
  | 'yaml'
  | 'json'
  | 'markdown'
  | 'html'
  | 'css'
  | 'scss'
  | 'vue'
  | 'svelte'
  | 'toml'
  | 'xml'
  | 'dockerfile'
  | 'terraform'
  | 'graphql'
  | 'proto'
  | 'unknown';

const BY_EXTENSION: Record<string, Language> = {
  '.ts': 'typescript',
  '.mts': 'typescript',
  '.cts': 'typescript',
  '.tsx': 'tsx',
  '.js': 'javascript',
  '.mjs': 'javascript',
  '.cjs': 'javascript',
  '.jsx': 'jsx',
  '.py': 'python',
  '.pyi': 'python',
  '.java': 'java',
  '.go': 'go',
  '.cs': 'csharp',
  '.rb': 'ruby',
  '.php': 'php',
  '.rs': 'rust',
  '.kt': 'kotlin',
  '.kts': 'kotlin',
  '.swift': 'swift',
  '.scala': 'scala',
  '.sql': 'sql',
  '.sh': 'shell',
  '.bash': 'shell',
  '.zsh': 'shell',
  '.ps1': 'shell',
  '.yml': 'yaml',
  '.yaml': 'yaml',
  '.json': 'json',
  '.jsonc': 'json',
  '.md': 'markdown',
  '.mdx': 'markdown',
  '.html': 'html',
  '.htm': 'html',
  '.css': 'css',
  '.scss': 'scss',
  '.sass': 'scss',
  '.less': 'scss',
  '.vue': 'vue',
  '.svelte': 'svelte',
  '.toml': 'toml',
  '.xml': 'xml',
  '.tf': 'terraform',
  '.tfvars': 'terraform',
  '.graphql': 'graphql',
  '.gql': 'graphql',
  '.proto': 'proto',
};

const BY_FILENAME: Record<string, Language> = {
  dockerfile: 'dockerfile',
  'docker-compose.yml': 'yaml',
  makefile: 'shell',
  'gemfile': 'ruby',
  'rakefile': 'ruby',
};

/** Languages we parse for symbols, chunk semantically and analyse. */
export const CODE_LANGUAGES: ReadonlySet<Language> = new Set<Language>([
  'typescript',
  'tsx',
  'javascript',
  'jsx',
  'python',
  'java',
  'go',
  'csharp',
  'ruby',
  'php',
  'rust',
  'kotlin',
  'swift',
  'scala',
  'vue',
  'svelte',
  'sql',
]);

export function detectLanguage(filePath: string): Language {
  const base = path.basename(filePath).toLowerCase();
  if (BY_FILENAME[base]) return BY_FILENAME[base] as Language;
  if (base.startsWith('dockerfile')) return 'dockerfile';
  const ext = path.extname(base);
  return (BY_EXTENSION[ext] as Language | undefined) ?? 'unknown';
}

export function isCodeLanguage(language: Language): boolean {
  return CODE_LANGUAGES.has(language);
}

export function displayLanguage(language: Language): string {
  const names: Partial<Record<Language, string>> = {
    typescript: 'TypeScript',
    tsx: 'TypeScript (TSX)',
    javascript: 'JavaScript',
    jsx: 'JavaScript (JSX)',
    python: 'Python',
    java: 'Java',
    go: 'Go',
    csharp: 'C#',
    ruby: 'Ruby',
    php: 'PHP',
    rust: 'Rust',
    kotlin: 'Kotlin',
    swift: 'Swift',
    scala: 'Scala',
    sql: 'SQL',
    shell: 'Shell',
    yaml: 'YAML',
    json: 'JSON',
    markdown: 'Markdown',
    html: 'HTML',
    css: 'CSS',
    scss: 'SCSS',
    vue: 'Vue',
    svelte: 'Svelte',
    toml: 'TOML',
    xml: 'XML',
    dockerfile: 'Dockerfile',
    terraform: 'Terraform',
    graphql: 'GraphQL',
    proto: 'Protobuf',
  };
  return names[language] ?? 'Other';
}

const TEST_PATH = /(^|\/)(tests?|__tests__|spec|e2e|cypress)(\/|$)/i;
const TEST_FILE = /\.(test|spec)\.[a-z]+$|_test\.[a-z]+$|^test_[^/]+\.py$|Test\.java$|Tests\.cs$/;

export function isTestFile(filePath: string): boolean {
  const base = path.basename(filePath);
  return TEST_PATH.test(filePath) || TEST_FILE.test(base);
}

const CONFIG_FILES = new Set([
  'package.json',
  'tsconfig.json',
  'jsconfig.json',
  'vite.config.ts',
  'vite.config.js',
  'webpack.config.js',
  'rollup.config.js',
  'next.config.js',
  'nest-cli.json',
  'jest.config.js',
  'jest.config.ts',
  'vitest.config.ts',
  'babel.config.js',
  '.eslintrc.json',
  '.eslintrc.js',
  'eslint.config.js',
  '.prettierrc',
  'requirements.txt',
  'pyproject.toml',
  'setup.py',
  'setup.cfg',
  'pipfile',
  'go.mod',
  'pom.xml',
  'build.gradle',
  'build.gradle.kts',
  'cargo.toml',
  'gemfile',
  'composer.json',
  'dockerfile',
  'docker-compose.yml',
  'docker-compose.yaml',
  'serverless.yml',
  'schema.prisma',
  '.env.example',
]);

export function isConfigFile(filePath: string): boolean {
  const base = path.basename(filePath).toLowerCase();
  if (CONFIG_FILES.has(base)) return true;
  if (base.endsWith('.csproj') || base.endsWith('.sln')) return true;
  return /(^|\/)(config|configs|conf)(\/|$)/i.test(filePath) && detectLanguage(filePath) !== 'unknown';
}

const GENERATED_MARKERS = [
  '@generated',
  'AUTO-GENERATED',
  'Code generated by',
  'DO NOT EDIT',
  'This file was automatically generated',
];

export function looksGenerated(content: string): boolean {
  const head = content.slice(0, 800);
  return GENERATED_MARKERS.some((marker) => head.includes(marker));
}

export interface RoleHint {
  role: string;
  reason: string;
}

/**
 * Assigns an architectural role from path + content conventions. Used to build
 * the project map and to rank retrieval results.
 */
export function detectRole(filePath: string, content: string): RoleHint {
  const p = filePath.toLowerCase();
  const base = path.basename(p);

  if (isTestFile(filePath)) return { role: 'test', reason: 'test path or filename convention' };
  if (/(^|\/)(migrations?|migrate)(\/|$)/.test(p)) return { role: 'migration', reason: 'migrations directory' };
  // "api" as a workspace name (apps/api, packages/api, services/api) says
  // nothing about the file's role - matching it labelled every backend file in
  // a monorepo "route" and collapsed the whole architecture view into one layer.
  const apiIsWorkspaceName = /(^|\/)(apps|packages|services|libs|modules|cmd)\/api(\/|$)/.test(p);
  if (
    /(^|\/)(routes?|router|routers|endpoints|controllers?|handlers?)(\/|$)/.test(p) ||
    (!apiIsWorkspaceName && /(^|\/)api(\/|$)/.test(p))
  ) {
    return { role: p.includes('controller') ? 'controller' : 'route', reason: 'routing/controller directory' };
  }
  if (/(^|\/)(middlewares?|interceptors?|guards?|filters?)(\/|$)/.test(p)) {
    return { role: 'middleware', reason: 'middleware directory' };
  }
  if (/(^|\/)(services?|usecases?|domain|business)(\/|$)/.test(p) || /service\.[a-z]+$/.test(base)) {
    return { role: 'service', reason: 'service layer convention' };
  }
  if (/(^|\/)(repositor(y|ies)|daos?|stores?|persistence)(\/|$)/.test(p) || /repository\.[a-z]+$/.test(base)) {
    return { role: 'repository', reason: 'data-access layer convention' };
  }
  if (/(^|\/)(models?|entities|schemas?|dtos?)(\/|$)/.test(p)) return { role: 'model', reason: 'model directory' };
  if (/(^|\/)(components?|views?|pages?|screens?|widgets?)(\/|$)/.test(p)) {
    return { role: 'component', reason: 'UI directory' };
  }
  if (/(^|\/)(hooks?|composables?)(\/|$)/.test(p)) return { role: 'hook', reason: 'hooks directory' };
  if (/(^|\/)(utils?|helpers?|lib|libs|common|shared)(\/|$)/.test(p)) {
    return { role: 'util', reason: 'utility directory' };
  }
  if (/(^|\/)(config|configs|settings)(\/|$)/.test(p) || isConfigFile(filePath)) {
    return { role: 'config', reason: 'configuration file' };
  }
  if (/(^|\/)(jobs?|workers?|tasks?|queues?|cron)(\/|$)/.test(p)) return { role: 'worker', reason: 'background job directory' };
  if (/(^|\/)(auth|authentication|authorization|security)(\/|$)/.test(p)) {
    return { role: 'auth', reason: 'authentication directory' };
  }

  if (/@(Controller|RestController)\b/.test(content)) return { role: 'controller', reason: 'framework controller annotation' };
  if (/@(Injectable|Service)\b/.test(content)) return { role: 'service', reason: 'framework service annotation' };
  if (/\b(app|router)\.(get|post|put|patch|delete)\s*\(/.test(content)) {
    return { role: 'route', reason: 'HTTP route registrations found in file' };
  }
  if (/\bexport\s+default\s+function\s+[A-Z]/.test(content) || /return\s*\(?\s*</.test(content)) {
    return { role: 'component', reason: 'renders JSX' };
  }

  // A conventional filename alone is not enough: most `index.ts` files are
  // re-export barrels, and labelling them entry points made whole directories
  // look like process entry points in the architecture view.
  const entry = ['main', 'index', 'app', 'server', 'program'].includes(base.split('.')[0] ?? '');
  if (entry) {
    const starts =
      /\.(listen|start|run)\s*\(|createServer\s*\(|createRoot\s*\(|ReactDOM\.render\s*\(|app\.mount\s*\(|if\s+__name__\s*==|func\s+main\s*\(|static\s+void\s+[Mm]ain\s*\(/.test(
        content,
      );
    if (starts) return { role: 'entrypoint', reason: 'conventional entry-point filename that starts the process' };
    if (/^\s*(import|export)\b/m.test(content) && !/\bfunction\b|\bclass\b/.test(content)) {
      return { role: 'barrel', reason: 're-export barrel' };
    }
  }

  return { role: 'unknown', reason: 'no convention matched' };
}
